name: stac-catalog-builder
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - affine=2.3.1
  - blosc=1.21.1
  - boost-cpp=1.78.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.9.24
  - cairo=1.16.0
  - certifi=2022.9.24
  - cfitsio=4.1.0
  - click=8.1.3
  - click-plugins=1.1.1
  - cligj=0.7.2
  - colorama=0.4.6
  - curl=7.86.0
  - exceptiongroup=1.0.4
  - expat=2.5.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - freexl=1.0.6
  - geos=3.11.1
  - geotiff=1.7.1
  - gettext=0.21.1
  - giflib=5.2.1
  - hdf4=4.2.15
  - hdf5=1.12.2
  - icu=70.1
  - jpeg=9e
  - json-c=0.16
  - kealib=1.4.15
  - keyutils=1.6.1
  - krb5=1.19.3
  - lcms2=2.14
  - ld_impl_linux-64=2.39
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.86.0
  - libdap4=3.20.6
  - libdeflate=1.14
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgdal=3.6.0
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libglib=2.74.1
  - libgomp=12.2.0
  - libiconv=1.17
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.8.1
  - libnghttp2=1.47.0
  - libnsl=2.0.0
  - libopenblas=0.3.21
  - libpng=1.6.38
  - libpq=14.5
  - librttopo=1.1.0
  - libspatialite=5.0.1
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libstdcxx-ng=12.2.0
  - libtiff=4.4.0
  - libuuid=2.32.1
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxml2=2.10.3
  - libzip=1.9.2
  - libzlib=1.2.13
  - lz4-c=1.9.3
  - ncurses=6.3
  - nspr=4.32
  - nss=3.78
  - numpy=1.23.4
  - openjpeg=2.5.0
  - openssl=3.0.7
  - pcre=8.45
  - pcre2=10.40
  - pip=22.3.1
  - pixman=0.40.0
  - poppler=22.11.0
  - poppler-data=0.4.11
  - postgresql=14.5
  - proj=9.1.0
  - pthread-stubs=0.4
  - pyparsing=3.0.9
  - python=3.11.0
  - python_abi=3.11
  - rasterio=1.3.4
  - readline=8.1.2
  - setuptools=65.5.1
  - snappy=1.1.9
  - snuggs=1.4.7
  - sqlite=3.40.0
  - tiledb=2.11.3
  - tk=8.6.12
  - tomli=2.0.1
  - tzcode=2022f
  - wheel=0.38.4
  - xerces-c=3.2.4
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - aiohttp==3.9.1
      - aiosignal==1.3.1
      - annotated-types==0.6.0
      - antimeridian==0.3.3
      - anyio==4.2.0
      - attrs==23.2.0
      - boto3==1.34.15
      - botocore==1.34.15
      - cffi==1.16.0
      - cfgv==3.4.0
      - charset-normalizer==3.3.2
      - cryptography==41.0.7
      - deprecated==1.2.14
      - distlib==0.3.8
      - editables==0.5
      - fancycompleter==0.9.1
      - filelock==3.13.1
      - fiona==1.9.5
      - frozenlist==1.4.1
      - fsspec==2023.12.2
      - geopandas==0.14.2
      - h11==0.14.0
      - hatch==1.9.1
      - hatchling==1.21.0
      - httpcore==1.0.2
      - httpx==0.26.0
      - humanfriendly==10.0
      - hyperlink==21.0.0
      - identify==2.5.33
      - idna==3.6
      - importlib-metadata==7.0.1
      - iniconfig==2.0.0
      - jaraco-classes==3.3.0
      - jeepney==0.8.0
      - jmespath==1.0.1
      - jsonschema==4.20.0
      - jsonschema-specifications==2023.12.1
      - keyring==24.3.0
      - lxml==5.1.0
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - more-itertools==10.2.0
      - multidict==6.0.4
      - nodeenv==1.8.0
      - openeo==0.26.0
      - packaging==23.2
      - pandas==2.1.4
      - pathspec==0.12.1
      - pdbpp==0.10.3
      - pexpect==4.9.0
      - platformdirs==4.1.0
      - pluggy==1.3.0
      - pre-commit==3.6.0
      - ptyprocess==0.7.0
      - pyarrow==14.0.2
      - pycparser==2.21
      - pydantic==2.5.3
      - pydantic-core==2.14.6
      - pygments==2.17.2
      - pyproj==3.6.1
      - pyrepl==0.9.0
      - pystac==1.8.4
      - pytest==7.2.2
      - python-dateutil==2.8.2
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - referencing==0.32.1
      - requests==2.31.0
      - requests-auth==7.0.0
      - rich==13.7.0
      - rio-stac==0.8.1
      - rpds-py==0.16.2
      - ruff==0.1.11
      - s3transfer==0.10.0
      - secretstorage==3.3.3
      - shapely==2.0.2
      - shellingham==1.5.4
      - six==1.16.0
      - sniffio==1.3.0
      - stac-catalog-builder==0.0.1
      - stac-validator==3.3.2
      - stactools==0.5.3
      - terracatalogueclient==0.1.14
      - tomli-w==1.0.0
      - tomlkit==0.12.3
      - trove-classifiers==2024.1.8
      - typing-extensions==4.9.0
      - tzdata==2023.4
      - urllib3==2.0.7
      - userpath==1.9.1
      - virtualenv==20.25.0
      - wmctrl==0.5
      - wrapt==1.16.0
      - xarray==2023.12.0
      - yarl==1.9.4
      - zipp==3.17.0
      - zstandard==0.22.0
