[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "STAC-Catalog-Builder"
version = "0.0.1"
authors = [
  { name="Johan Schreurs", email="johan.schreurs.ext@vito.be" },
]
description = """Tool to build a STAC collection from a directory of GeoTiff files
STAC: SpatioTemporal Asset Catalogs
See https://stacspec.org
"""
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]

[tool.black]
line-length = 120

[tool.isort]
# Run isort in black-compatible mode (https://pycqa.github.io/isort/docs/configuration/black_compatibility.html)
profile = "black"

[tool.ruff]
line-length = 120
