[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "STAC-Catalog-Builder"
version = "0.0.1"
authors = [
  { name="Johan Schreurs", email="johan.schreurs.ext@vito.be" },
  { name="Jeroen Dries", email="jeroen.dries@vito.be" },
]
description = """Tool to build a STAC collection from a directory of GeoTiff files
STAC: SpatioTemporal Asset Catalogs
See https://stacspec.org
"""
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]

[project.urls]
Documentation = "https://github.com/VitoTAP/stac-catalog-builder#readme"
Issues = "https://github.com/VitoTAP/stac-catalog-builder/issues"
Source = "https://github.com/VitoTAP/stac-catalog-builder"


[tool.hatch.build.targets.wheel]
packages = ["stacbuilder"]

[tool.hatch.build.targets.sdist]
include = [
  "/stacbuilder",
]
exclude = [
  "/.github",
  "/docs",
  "/tests",
  "/configs-datasets",
]

[tool.hatch.version]
path = "stacbuilder/_version.py"

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-ra"
testpaths = [
    "tests",
]

[tool.black]
line-length = 120

[tool.isort]
# Run isort in black-compatible mode (https://pycqa.github.io/isort/docs/configuration/black_compatibility.html)
profile = "black"

[tool.ruff]
line-length = 120
