name: Run Pytest

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: stac-catalog-builder
        environment-file: conda-environment.yaml
        auto-activate-base: false
    - name: Install dependencies
      run: |
        conda env update --file conda-environment.yaml
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
